### ISSUE TITLE
Katze wieder öffnen

### ISSUE THREAD

**Issue by xProxyRed** [Leetcore/ninja-hacker-cat#5]
Moin, ich bin gerade etwas überfragt. 
Ich habe die Katze und sie ist ja echt super. nun hatte ich sie zu gemacht weil ich sie net brauchte. jetzt wollte ich wieder was testen und gemerkt das ich zu blöd bin wieder zu öffnen. gibt es da ein trick?

**Comment by Leetcore** [comment]
Hey, in der neuen Version sollte in deiner Toolbar eine kleine Katze sein und wenn man da drauf klickt, geht sie wieder auf. Falls du die ältere Version hast mit der Sidebar, dann auf Ansicht > Sidebar.
