### ISSUE TITLE
Ninja Hacker Cat starts spamming.

### ISSUE THREAD

**Issue by K1ZANA** [Leetcore/ninja-hacker-cat#8]
If you open a website, Ninja Hacker Cat repeatly sends the robots.txt info. (Stops after a reload of the panel)

**Comment by Leetcore** [comment]
Can you update to version 1.7?

**Comment by K1ZANA** [comment]
It just updated actually, bug´s gone.
I originally thought it would be because of my browser, i use Waterfox instead of firefox.
Thanks tho 😄
